const fs=require('fs'),path=require('path'),crypto=require('crypto');
const [work,tooling]=process.argv.slice(2),ROOT=path.resolve(__dirname,'../../..'),V5=path.resolve(__dirname,'..');
const {NodeIO}=require(path.join(tooling,'@gltf-transform/core')),{ALL_EXTENSIONS}=require(path.join(tooling,'@gltf-transform/extensions')),{dedup,prune,weld,meshopt}=require(path.join(tooling,'@gltf-transform/functions')),{MeshoptEncoder,MeshoptDecoder}=require(path.join(tooling,'meshoptimizer')),validator=require(path.join(tooling,'gltf-validator'));
(async()=>{await MeshoptEncoder.ready;await MeshoptDecoder.ready;const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder,'meshopt.decoder':MeshoptDecoder});const reports=[];
for(const kind of ['boomerang','park']){const input=path.join(work,kind==='park'?'park-v5-static.glb':'boomerang-raw.glb');if(!fs.existsSync(input)){console.log('pending',kind);continue;}const doc=await io.read(input),root=doc.getRoot(),buffer=root.listBuffers()[0],nodes=Object.fromEntries(root.listNodes().map(n=>[n.getName(),n]));
function accessor(name,type,values){return doc.createAccessor(name).setType(type).setArray(new Float32Array(values)).setBuffer(buffer)}
function channel(anim,node,name,property,times,type,values){const sampler=doc.createAnimationSampler().setInput(accessor(name+' time','SCALAR',times)).setOutput(accessor(name+' '+property,type,values)).setInterpolation('LINEAR');anim.addSampler(sampler).addChannel(doc.createAnimationChannel().setTargetNode(node).setTargetPath(property).setSampler(sampler));}
if(kind==='park'){
 const m=JSON.parse(fs.readFileSync(path.join(ROOT,'design/v4/scene-manifest.json'),'utf8')),build=doc.createAnimation('Park_Construction');
 for(const [name,[a,b]] of Object.entries(m.park_stages)){const n=nodes[name];if(!n)throw Error(name);n.setScale([1,1,1]);const t=[...new Set([0,a,b,15])],v=[];for(const x of t){const s=x<=a?.001:1;v.push(...(name.startsWith('wheel-')?[s,s,s]:[1,s,1]));}channel(build,n,name,'scale',t,'VEC3',v);}
 const spin=doc.createAnimation('Wheel_Rotation');for(const name of ['wheel-rotor',...Array.from({length:36},(_,i)=>'wheel-cabin-'+String(i).padStart(2,'0'))]){const n=nodes[name];if(!n)throw Error(name);n.setRotation([0,0,0,1]);const t=[],v=[],sign=name==='wheel-rotor'?-1:1;for(let i=0;i<=120;i++){const p=i/120;t.push(p*60);v.push(0,0,sign*Math.sin(p*Math.PI),Math.cos(p*Math.PI));}channel(spin,n,name,'rotation',t,'VEC4',v);}
 const wind=doc.createAnimation('Flags_Wind');for(const n of root.listNodes().filter(n=>n.getName().startsWith('FLAG_'))){if(!n.getMesh()||n.getMesh().listPrimitives()[0].listTargets().length!==2)throw Error('Flag morph mismatch '+n.getName());n.setWeights([0,0]);channel(wind,n,n.getName(),'weights',[0,4/3,8/3,4],'SCALAR',[0,0,1,0,0,1,0,0]);}
}
await doc.transform(dedup(),weld(),prune(),meshopt({encoder:MeshoptEncoder,level:'high'}),dedup(),prune());const output=path.join(ROOT,'public/models',kind==='park'?'muscat-park-v5.glb':'boomerang-v5.glb');await io.write(output,doc);const data=fs.readFileSync(output);const compressed=await validator.validateBytes(data,{maxIssues:50});const reread=await io.read(output);for(const ext of reread.getRoot().listExtensionsUsed())if(ext.extensionName==='EXT_meshopt_compression')ext.dispose();const decoded=await validator.validateBytes(await io.writeBinary(reread),{maxIssues:50});const report={file:path.basename(output),bytes:data.length,sha256:crypto.createHash('sha256').update(data).digest('hex'),meshes:root.listMeshes().length,nodes:root.listNodes().length,materials:root.listMaterials().length,textures:root.listTextures().length,clips:root.listAnimations().map(a=>({name:a.getName(),channels:a.listChannels().length,duration_s:Math.max(...a.listSamplers().map(s=>s.getInput().getMax([])[0]))})),compressed:compressed.issues,decoded:decoded.issues};reports.push(report);console.log(JSON.stringify({file:report.file,bytes:report.bytes,errors:decoded.issues.numErrors,warnings:decoded.issues.numWarnings,clips:report.clips}));}
fs.writeFileSync(path.join(V5,'web-export-validation.json'),JSON.stringify(reports,null,2));})();
