import {readFile,stat,readdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../out');
const html=await readFile(path.join(root,'index.html'),'utf8');
if(!html.includes('/muscat-amusement-park/'))throw new Error('Expected static base path');
for(const name of ['models/muscat-park-v4.glb','models/muscat-wheel-v4.glb','media/v4/google-site.svg','media/v4/model-aerial.webp','media/v4/vision-aerial.webp','media/v4/wheel-mountains.webp','media/v4/wheel-poster.webp','media/v4/zone-rides.webp','media/v4/zone-water.webp','media/v4/zone-city.webp','media/v4/zone-parking.webp','media/v4/zone-utility.webp','fonts/IBMPlexSansArabic-Regular.woff2','media/masterplan-v3.svg','data/design-references.json','references/index.html'])if(!(await stat(path.join(root,name))).isFile())throw new Error('Missing runtime asset: '+name);
const glb=await readFile(path.join(root,'models/muscat-park-v4.glb'));
if(glb.toString('ascii',0,4)!=='glTF'||glb.readUInt32LE(4)!==2||glb.readUInt32LE(8)!==glb.length)throw new Error('Invalid GLB header');
const scene=JSON.parse(glb.toString('utf8',20,20+glb.readUInt32LE(12)));
for(const x of [...(scene.buffers||[]),...(scene.images||[])])if(x.uri&&!x.uri.startsWith('data:'))throw new Error('External GLB dependency');
if(!scene.animations?.some(a=>a.name==='Park_Construction')||!scene.animations?.some(a=>a.name==='Wheel_Rotation'))throw new Error('Missing park animations');
const wheel=await readFile(path.join(root,'models/muscat-wheel-v4.glb'));
const wheelScene=JSON.parse(wheel.toString('utf8',20,20+wheel.readUInt32LE(12)));
if(!wheelScene.animations?.some(a=>a.name==='Wheel_Construction')||!wheelScene.animations?.some(a=>a.name==='Wheel_Rotation'))throw new Error('Missing wheel animations');
if(!html.includes('Muscat Amusement Park (MAP)'))throw new Error('Old brand');
if(!html.includes('بناء المجسم')||/Ш§|Щ„|вЂ/.test(html))throw new Error('Arabic encoding regression');
let files=0,bytes=0;
async function inspect(folder){for(const entry of await readdir(folder,{withFileTypes:true})){if(entry.isSymbolicLink())throw new Error('Unexpected export symlink');const full=path.join(folder,entry.name);if(entry.isDirectory())await inspect(full);else {if(/\.(srt|blend|py|ps1|pem|key|map)$/i.test(entry.name)||entry.name==='site-content.json'||entry.name.startsWith('.env'))throw new Error('Private/source file in static export');files++;bytes+=(await stat(full)).size;}}}
await inspect(root);
console.log(JSON.stringify({status:'passed',basePath:'/muscat-amusement-park/',files,bytes,glb:'self-contained v4'},null,2));
